apiVersion: v1
kind: ConfigMap
metadata:
  name: product-service-config
  namespace: shoeapp
data:
  SERVER_PORT: "8081"
  SPRING_APPLICATION_NAME: "product-service"
  SPRING_DATASOURCE_URL: "jdbc:postgresql://postgres-product:5432/product_db"
  SPRING_DATASOURCE_USERNAME: "product_user"
  EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: "http://discovery-server:8761/eureka/"
