apiVersion: v1
kind: ConfigMap
metadata:
  name: cart-service-config
  namespace: shoeapp
data:
  SERVER_PORT: "8085"
  SPRING_APPLICATION_NAME: "cart-service"
  SPRING_DATA_REDIS_HOST: "redis"
  SPRING_DATA_REDIS_PORT: "6379"
  EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: "http://discovery-server:8761/eureka/"
