apiVersion: v1
kind: ConfigMap
metadata:
  name: auth-service-config
  namespace: shoeapp
data:
  SERVER_PORT: "8084"
  SPRING_APPLICATION_NAME: "auth-service"
  SPRING_DATASOURCE_URL: "jdbc:postgresql://postgres-auth:5432/auth_db"
  SPRING_DATASOURCE_USERNAME: "auth_user"
  EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: "http://discovery-server:8761/eureka/"
