apiVersion: v1
kind: ConfigMap
metadata:
  name: notification-service-config
  namespace: shoeapp
data:
  SERVER_PORT: "8087"
  SPRING_APPLICATION_NAME: "notification-service"
  SPRING_KAFKA_BOOTSTRAP_SERVERS: "kafka:9092"
  EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: "http://discovery-server:8761/eureka/"
  MAIL_HOST: "smtp.gmail.com"
  MAIL_PORT: "587"
  MAIL_FROM: "noreply@shoeapp.com"
