apiVersion: apps/v1
kind: Deployment
metadata:
  name: payment-service
  namespace: shoeapp
  labels:
    app: payment-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: payment-service
  template:
    metadata:
      labels:
        app: payment-service
    spec:
      containers:
        - name: payment-service
          image: yourname/payment-service:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8086
          envFrom:
            - configMapRef:
                name: payment-service-config
          env:
            - name: SPRING_DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: payment-db-secret
                  key: password
            - name: STRIPE_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: shoeapp-shared-secrets
                  key: stripe-secret-key
            - name: OTEL_EXPORTER_OTLP_ENDPOINT
              value: "http://jaeger:4317"
            - name: OTEL_SERVICE_NAME
              value: "payment-service"
          resources:
            requests:
              cpu: "250m"
              memory: "384Mi"
            limits:
              cpu: "500m"
              memory: "768Mi"
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 8086
            initialDelaySeconds: 40
            periodSeconds: 10
            failureThreshold: 3
          livenessProbe:
            httpGet:
              path: /actuator/health
              port: 8086
            initialDelaySeconds: 90
            periodSeconds: 15
            failureThreshold: 3
