apiVersion: v1
kind: ConfigMap
metadata:
  name: user-service-config
  namespace: shoeapp
data:
  SERVER_PORT: "8088"
  SPRING_APPLICATION_NAME: "user-service"
  SPRING_DATASOURCE_URL: "jdbc:postgresql://postgres-user:5432/user_db"
  SPRING_DATASOURCE_USERNAME: "user_user"
  EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: "http://discovery-server:8761/eureka/"
